import { randomBytes } from "node:crypto";

/** Generated by the server; never reuse an incoming client-provided nonce. */
export function createCspHeaders(incoming: Headers, portal: "web" | "admin") {
  const nonce = randomBytes(24).toString("base64");
  const development = process.env.NODE_ENV === "development";
  const policy = [
    "default-src 'self'",
    `script-src 'self' 'nonce-${nonce}' 'strict-dynamic'${development ? " 'unsafe-eval'" : ""}`,
    "script-src-attr 'none'",
    "style-src 'self' 'unsafe-inline'",
    "img-src 'self' data: blob: https://*.supabase.co https://*.vimeocdn.com https://images.unsplash.com",
    "font-src 'self' data:",
    `connect-src 'self' https://*.supabase.co wss://*.supabase.co${portal === "web" ? " https://*.vimeo.com" : ""}${development ? " ws://localhost:*" : ""}`,
    `frame-src ${portal === "web" ? "https://player.vimeo.com" : "'none'"}`,
    "media-src 'self' blob: https://*.vimeo.com https://*.vimeocdn.com",
    "object-src 'none'", "base-uri 'self'", "form-action 'self'", "frame-ancestors 'none'",
    ...(!development ? ["upgrade-insecure-requests"] : []),
  ].join("; ");
  const headers = new Headers(incoming);
  headers.set("x-nonce", nonce);
  headers.set("Content-Security-Policy", policy);
  return { headers, policy };
}
